version: "3.9"
services:
  db:
    image: postgres:16
    container_name: floorreports_pg
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: app
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  adminer:
    image: adminer:4
    container_name: floorreports_adminer
    depends_on: [db]
    ports: ["8080:8080"]
volumes:
  pgdata:
